### ISSUE TITLE
Possibility of supporting AOSP/LOS Contacts

### ISSUE THREAD

**Issue by moriel5** [benrap/GoogleContactsQR#1]
This is awesome, but could you please add support for the AOSP/LOS (etc.) Contacts apps?
I'm guessing that things should be identical, with the only additions to your code would for adding "com.android.contacts", in addition to "com.google.android.contacts".

Update: It would be best if I had first checked if custom ROMs even have this feature.

**Comment by benrap** [comment]
You're welcome to fork my extremely simple code. Unfortunately I am busy nowadays, so I cannot tend to it myself.
